import time
import random
choixSortie = "Rien"
while choixSortie != "QUITTER":
    joueur = input("Mais au fait, comment t'appelle tu ? : ")
    print(f"Tu t'appelle : {joueur}")
    joueur = joueur.upper()
    print("...")
    time.sleep(1.5)
    print("...")
    time.sleep(1.5)
    print("...")
    time.sleep(1.5)
    print("KING ROY        ...")
    print(f"KING ROY        Merci de m'avoir accepté,{joueur.lower()}")
    time.sleep(2.5)
    print(f"{joueur}        De rien, c'est naturel. ( Et en plus, il est super fort 0:))")
    time.sleep(2)
    print("Vous marchez vers le centre du pays")
    time.sleep(1.5)
    print("KING ROY        Attention !!!!!")
    time.sleep(1.3)
    print()
    print("--------------------")
    print("COMBAT V.S. SLIME X10")
    print("--------------------")
    print()
    chance = random.randint(0,10)
    if chance >= 4 :
        time.sleep(2.3)
        print(f"{joueur}      Les slimes je vais vous battre pour gagner un peu de puissance")
        time.sleep(2)
        print(f"{joueur}      Un de mort")
        time.sleep(1)
        print(f"{joueur}      ...")
        time.sleep(2)
        print(f"{joueur}      ...")
        time.sleep(2)
        print(f"{joueur}      Et les autres aussi")
        time.sleep(2)
        print(f"Vous gagnez 1000 en puissance")
    else:
        print(f"{joueur} je veux les battres")
        time.sleep(2)
        print(f"{joueur}      ...")
        time.sleep(2)
        print(f"{joueur}      ...")
        time.sleep(2)
        print(f"{joueur}      ...")
        time.sleep(2)
        print("KING ROY        Oh tu es presque mort laisse moi m'en charger.")
        time.sleep(1.7)
        print("\033[35mVous regardez merveilleusement King Roy faire un bond et retomber en attaquant les slimes d'un coup !!\033[0m")
        time.sleep(3.5)
        print("KING ROY        Ahlala, les slimes sont coriaces ici...")
        time.sleep(1.9)
        print(f"{joueur}        Ah.... C'est coriace...")
    time.sleep(1.7)
    print("Ce combat était en chance")
    time.sleep(1.7)
    print("Il y a deux chemins : 1 : une redoutable grotte et 2 : une jolie clairière...")
    time.sleep(2.5)
    choixJoueur1 = input("Entre 1 ou 2...")
    if choixJoueur1 == "1":
        print("KING ROY        Brrrrrrrrr, il fait froid, mais on se sent bien.")
        time.sleep(1.7)
        print(f"{joueur}        Oui, c'est chaleureux, pas comme on le croyait...")
        time.sleep(2)
        print("KING ROY        Par contre, je crois qu'on est perdus...")
        time.sleep(2)
        print(f"{joueur}        Ah. Bon, on fait quoi ?")
        time.sleep(1.5)
        print("Vous cherchez pendant des heures la sortie, jusqu'a un embranchement.")
        time.sleep(2.6)
        print("Pour aller à gauche, c'est 1 et pour la droite, c'est 2")
        time.sleep(2.3)
        choixJoueur2 = input("Entre 1 ou 2")
        if choixJoueur2 == "1":
            print("KING ROY        Du coup, c'est la gauche.")
            time.sleep(2)
            print(f"{joueur}        Yep ! C'est parti !")
            time.sleep(1.7)
            print("???        Grooooaaaaaarrr !!!!!")
            time.sleep(1.7)
            print(f"{joueur}        Que'est-ce qui se passe !!!")
            time.sleep(1.7)
            print("KING ROY        UN LOUP DES TENEBRES !!!!!!!!!")
            time.sleep(1.7)
            print(f"{joueur}        AAAAAAAIIIIIIEEEEEEE !!!!")
            time.sleep(1.7)
            print("Vous partez et vous vous enfuyez de la grotte.")
            time.sleep(2.5)
        elif choixJoueur2 == "2":
            print("KING ROY        Droite ! Youhou !")
            time.sleep(1.5)
            print(f"{joueur}        Yes !")
            time.sleep(1.3)
            print("Vous continuez et trouvez la sortie, mais la fatique vous gagne et vous sombrez dans le sommeil profond...")
            time.sleep(4)
    elif choixJoueur1 == "2":
        print("KING ROY        Oh... C'est joli ici...")
        time.sleep(1.5)
        print(f"{joueur}        Oui...")
        time.sleep(1)
        print("???        BZZZZZZZZZZZZZZ")
        time.sleep(2)
        print(f"{joueur}        Hein ??????")
        time.sleep(1.7)
        print("KING ROY        AHHHHHHHHHH !!!!! DES ABEILLES TUEUSES !!!!!!!!")
        time.sleep(2.7)
        print("ABEILLES TUEUSES        BZZZZZZZZZZZZZZZZZ")
        time.sleep(2.5)
        print(f"{joueur}        Aïe Aïe Aïe !!!!")
        time.sleep(2.3)
        print("Vous vous faîtes piquez et vous vous enfuyez de la clairière...")
        time.sleep(3.3)
        print("KING ROY        Bon... Ca va ???")
        time.sleep(2.3)
        print(f"{joueur}        Oui, merci... J'ai été piqué...")
        time.sleep(3)
        print("KING ROY        QUOOOOOIIIIII !!!!!! Vite, allons au château !")
        time.sleep(3.7)
    else:
        print("Tu n'as pas entré 1 ou 2... Recommence mon aventure !")
    print("KING ROY        Mon pauvre... Tu as tout donné, on arrive...")
    time.sleep(3)
    print(f"{joueur}     Zzzzzzz")
    print(f"{joueur.lower()} dort")
    time.sleep(1)
    print("KING ROY        Mo...mon...mon châ...MON CHATEAU !!!!!!!!!")
    time.sleep(2.5)
    print("Vous êtes réveillé par King Roy qui crie à la mort. Son château à été détruit !")
    time.sleep(3.7)
    print("Il vous laisse à l'infiermerie et court voir le château. Vous le suivez après avoir été soigné")
    time.sleep(4)
    print("???        J'ai réussi... Je l'ai détruit...")
    time.sleep(3)
    print("???        QUI OSE ME DERANGER ????")
    time.sleep(2)
    print("KING ROY        Qui à détruit mon château ???!!!")
    time.sleep(3)
    print("???        Moi........")
    time.sleep(2)
    print("???        Et mon nom est :")
    time.sleep(3)
    print()
    print("FIN DU CHAPITRE 1 ! MERCI DE ME SOUTENIR ! LA VERSION 2 EST EN PREPARATION !")
    choixSortie = input("Appuie sur Entrée pour rejouer ou tape QUITTER pour arrêter")
    
